language: node_js
node_js:
- '12'
dist: trusty
branches:
  only:
  - master
script:
- yarn run lint
- yarn run build

deploy:
  provider: firebase
  token:
    secure: 1GeE59r2jvqqAKzaqkgu1/09+H1hrCptlMgkvmFrIW1roX/ck7VUZcSbCkytvMEPR5ybb1H4m85e+N9ck5pk9v7B/QLowRFt4/BRpnWADE258gQfYVgM7ZHPCUvQ6t4eeddrSSjTVDwGyYr+qCzq4CuvTihgM9phehmKHXr+Ghx5OzftJaUGpI9Nd+fa8/5ty/4t6QYNONIq+5rHfmobj5vuSPuXzdT2u1PPNRVRwCEDisVYE+U1tesgX5xh8sr+Z5nJKqZ9AX+6ZaYMbm2BMYDTQMt+GIacR3RBWXBYiq6rOgP72G6nklgIAdu9oDwwZfUqLOFFj4/0t7uN0fEQQ5G6P0kEISmp+8ERad5WUUFFzR7GluYAKTwTBQ07vwea54CxjwkNw2UAMJS/ohISNAu1nBsQPlpVget+DoWbVduYJbfY93JDeiKqjLz8FTDxSFqjFMdWy6le509qmW/4+/Iyy0oyOGKZehz3okC5QgHLuT6Ij1NivyZEOzYblbVCWc3raNqzGbIjEEJVEPSI1hw+3IMlPxJQVNOhXWjEryWTlzwtFcD8VCwhEo954ukg9LE6d5fDL784TAhsZ5OAXNcpUqlzOBC+cWnA5pKqk02ndOTD0t7W4zlRduhnwrmlA67QwexW58cImkmk3Voj7wZdPlHrpde2IkVbS/ZikXo=
