language: node_js

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"

node_js:
  - '14't
branches:
  only:
  - master
script:
- yarn run lint
- yarn run build

deploy:
  skip_cleanup: true
  provider: firebase
  token:
  secure: "Wm93dLNjQoRirZBROoTuySznX1dd+7t4GJNPyaERtrjYm69jajCtXHGkYrizxr8C3nto5ixFP5+7sBFlocNhAP343dAwUceHssAlSQPrk9hHvi1Q/kBrtTvi/2Jes9aiNM7RWrLCVX6BPgpar3qcTQ0U2ue3XfOuh0BVvNhMOsqgdfDomKbjAyz2VKmAtZULwQBVjardpma1z0rX/C5GuqV6TrETGvzdJqvAVLfwAoeiJrWyIszPkf2UYRi7yQ3J9Y4kTnL4MzfZa0ni2Gryvv33cieSeuKBGp8u1Ni3lVasMO2JvvcnvCWdWR6gB/NQixRSvZXKyZii0FrNwiAIsI/PbOnjM/gJH5yD+GDSQNrV5OZvDsQ5zGMjkLQ1/ccl/juv6Hex4Oh2Kw7JTSXgogwk4PH8RawdgHhHyiZTBRuLy1WocqVEIhbQu6pwsEyN4a0+V1nlMddVh5TQaaLLXQhDFmqCMm7uTQ1P/HKZDmafB6w5j8TOb9IVXDnnAhtzDMIBufUX40S8cF6X/Jw6IU9kinEsXTjJVhn56nlBYFYb7M1VUt+kkfiITj+I4dZsF6wF7jDMjv/R1c92MfDTWsKPCXNaXrOTamm3Q/MCWHAf/+Mjx8uB3z1fvcBuial+i7Y02xTgOW7i4I8h50ZxDJA4rjBgALI1KHmwShrBktE="
