language: node_js
node_js:
- '16'
branches:
  only:
  - master
script:
- yarn run lint
- yarn run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: ypPbfr0pY04f5QpKvNnh/lsoT6aOtZedckvOEViN9i1hQzgF94IUA9D1YaZZ9U4pvKShoEOjzI+F9FPXknslizo3O45lI97YDu0/zlw0CzFCG+Cm72rOXheG5jzEolWPPfWVy9HiN8vxrCGSMgIyEPYH+0GTI5Z0fsKOlt9TRJBHAqswLVQriNdWpabw7Ni7+t3FDFvAqlC5ug75LrwgiveA5PaSA57nyjQieCFtu+HGADdQJec8Kjjd3Ve/W3QjF5rs2EhN8r4+HkBJyOexyqR1SuF1iEkorUgLzZsboQoo2I0WRuMdcjLlcfsq8F5tpSIpd5VoW07H7QtPd+Zw/NrGR6CTd+Zf6R5dlt8VwpYBtUH5FM2d5wAGJI3pDQY/sDOGMAaVk38DzG/ToVCF4jbMHhVgSaBDVlAknj7drvekrz+jCCI01fJGFcmoMLZYh5vPhgJO+9/sQii6sFeHkCdz7Sa4Ox1Owi7sjPiR6k83c5snLwqHy7JrEPZ6hqlY2j4AxkwWbeAL0LveQwQcVXzJzWwIcQSLYd1iCtM/Vlj0z2o2TwBVqpkyuaVS5ugn/95tO6wikvAZnDo7bLr8H/IEVutyL4i5tbepOtLv58u04kTiw1df9Lu/JYcfaKL2OlNwnJLQAldOXrlBY7F54RUdjGvFsJA6FfDbtAcCeBs=
